import 'package:get/get.dart';

class Localization extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        'en': {
          'auth.signInButton': 'Sign In',
          'auth.signUpButton': 'Sign Up',
          'auth.resetPasswordButton': 'Send Password Reset',
          'auth.emailFormField': 'Email',
          'auth.passwordFormField': 'Password',
          'auth.nameFormField': 'Name',
          'auth.signInErrorTitle': 'Sign In Error',
          'auth.signInError': 'Login failed: email or password incorrect.',
          'auth.resetPasswordLabelButton': 'Forgot password?',
          'auth.signUpLabelButton': 'Create an Account',
          'auth.signUpErrorTitle': 'Sign Up Failed.',
          'auth.signUpError':
              'There was a problem signing up.  Please try again later.',
          'auth.signInLabelButton': 'Have an Account? Sign In.',
          'auth.resetPasswordNoticeTitle': 'Password Reset Email Sent',
          'auth.resetPasswordNotice':
              'Check your email and follow the instructions to reset your password.',
          'auth.resetPasswordFailed': 'Password Reset Email Failed',
          'auth.signInonResetPasswordLabelButton': 'Sign In',
          'auth.updateUser': 'Update Profile',
          'auth.updateUserSuccessNoticeTitle': 'User Updated',
          'auth.updateUserSuccessNotice':
              'User information successfully updated.',
          'auth.updateUserEmailInUse':
              'That email address already has an account.',
          'auth.updateUserFailNotice': 'Failed to update user',
          'auth.enterPassword': 'Enter your password',
          'auth.cancel': 'Cancel',
          'auth.submit': 'Submit',
          'auth.changePasswordLabelButton': 'Change Password',
          'auth.resetPasswordTitle': 'Reset Password',
          'auth.updateProfileTitle': 'Update Profile',
          'auth.wrongPasswordNoticeTitle': 'Login Failed',
          'auth.wrongPasswordNotice':
              'The password does not match our records.',
          'auth.unknownError': 'Unknown Error',
          'settings.title': 'Settings',
          'settings.language': 'Language',
          'settings.theme': 'Theme',
          'settings.signOut': 'Sign Out',
          'settings.dark': 'Dark',
          'settings.light': 'Light',
          'settings.system': 'System',
          'settings.updateProfile': 'Update Profile',
          'home.title': 'Home',
          'home.nameLabel': 'Name',
          'home.uidLabel': 'UID',
          'home.emailLabel': 'Email',
          'home.adminUserLabel': 'Admin User',
          'app.title': 'Flutter Starter Project',
          'validator.email': 'Please enter a valid email address.',
          'validator.password': 'Password must be at least 6 characters.',
          'validator.name': 'Please enter a name.',
          'validator.number': 'Please enter a number.',
          'validator.notEmpty': 'This is a required field.',
          'validator.amount':
              'Please enter a number i.e. 250 - no dollar symbol and no cents',
          'thorn.name': 'Happy',
          'thorn.smile': 'Me',
        },
        'km': {
          'auth.signInButton': 'ចូល',
          'auth.signUpButton': 'ចុះ​ឈ្មោះ',
          'auth.resetPasswordButton': 'ផ្ញើកំណត់ពាក្យសម្ងាត់ឡើងវិញ',
          'auth.emailFormField': 'អ៊ីមែល',
          'auth.passwordFormField': 'ហក្យសមងាត់',
          'auth.nameFormField': 'ឈ្ផោហ',
          'auth.signInErrorTitle': 'ចូលក្នុងកំហុស',
          'auth.signInError':
              'ការចូលបានបរាជ័យ: អ៊ីមែលឬពាក្យសម្ងាត់មិនត្រឹមត្រូវ។',
          'auth.resetPasswordLabelButton': 'ភ្លេច​លេខសំងាត់​?',
          'auth.signUpLabelButton': 'បង្កើត​គណនី',
          'auth.signUpErrorTitle': 'ចុះឈ្មោះបានបរាជ័យ។',
          'auth.signUpError':
              'មានបញ្ហាក្នុងការចុះឈ្មោះ។ សូម​ព្យាយាម​ម្តង​ទៀត​នៅ​ពេល​ក្រោយ។',
          'auth.signInLabelButton': 'មានគណនីមួយ? ចូល។',
          'auth.resetPasswordNoticeTitle': 'កំណត់អ៊ីមែលកំណត់ពាក្យសម្ងាត់',
          'auth.resetPasswordNotice':
              'ពិនិត្យអ៊ីមែលរបស់អ្នកហើយធ្វើតាមការណែនាំដើម្បីកំណត់ពាក្យសម្ងាត់របស់អ្នកឡើងវិញ។',
          'auth.resetPasswordFailed': 'កំណត់អ៊ីមែលកំណត់ពាក្យសម្ងាត់បានបរាជ័យ',
          'auth.signInonResetPasswordLabelButton': 'ចូល',
          'auth.updateUser': 'ធ្វើបច្ចុប្បន្នភាពទម្រង់',
          'auth.updateUserSuccessNoticeTitle': 'អ្នកប្រើបានធ្វើបច្ចុប្បន្នភាព',
          'auth.updateUserSuccessNotice':
              'ព័ត៌មានអ្នកប្រើប្រាស់បានធ្វើបច្ចុប្បន្នភាពដោយជោគជ័យ។',
          'auth.updateUserEmailInUse': 'អាសយដ្ឋានអ៊ីមែលនោះមានគណនីរួចហើយ។',
          'auth.updateUserFailNotice':
              'បានបរាជ័យក្នុងការធ្វើបច្ចុប្បន្នភាពអ្នកប្រើប្រាស់',
          'auth.enterPassword': 'បញ្ចូលពាក្យសម្ងាត់របស់អ្នក',
          'auth.cancel': 'លប់ចោល',
          'auth.submit': 'ដាក់រេកាមបង្គាប់',
          'auth.changePasswordLabelButton': 'ផ្លាស់ប្តូរលេខសម្ងាត់',
          'auth.resetPasswordTitle': 'កំណត់ពាក្យសម្ងាត់ឡើងវិញ',
          'auth.updateProfileTitle': 'ធ្វើបច្ចុប្បន្នភាពទម្រង់',
          'auth.wrongPasswordNoticeTitle': 'បានបរាជ័យ',
          'auth.wrongPasswordNotice':
              'ពាក្យសម្ងាត់មិនត្រូវគ្នានឹងកំណត់ត្រារបស់យើងទេ។',
          'auth.unknownError': 'កំហុសមិនស្គាល់',
          'settings.title': 'ការកំណត់',
          'settings.language': 'ផាសា',
          'settings.theme': 'និក្ខេបត',
          'settings.signOut': 'ចាកចេញ',
          'settings.dark': 'ងងឹត',
          'settings.light': 'ខ្ចី',
          'settings.system': 'របប័ន្ធ',
          'settings.updateProfile': 'ធ្វើបច្ចុប្បន្នភាពទម្រង់',
          'home.title': 'ផ្ទហ',
          'home.nameLabel': 'ឈ្ផោហ',
          'home.uidLabel': 'យូ',
          'home.emailLabel': 'អ៊ីមែល',
          'home.adminUserLabel': 'អ្នកប្រើរដ្ឋបាល',
          'app.title': 'គម្រោងចាប់ផ្តើមរអិល',
          'validator.email': 'សូមបញ្ចូលអាសយដ្ឋានអ៊ីមែលត្រឹមត្រូវ។',
          'validator.password': 'លេខសម្ងាត់ត្រូវតែមានយ៉ាងហោចណាស់ 6 តួអក្សរ។',
          'validator.name': 'សូមបញ្ចូលឈ្មោះមួយ។',
          'validator.number': 'សូមបញ្ចូលលេខមួយ។',
          'validator.notEmpty': 'នេះគឺជាវាលដែលត្រូវការ។',
          'validator.amount':
              'សូមបញ្ចូលលេខ I.e. 250 - គ្មាននិមិត្តសញ្ញាដុល្លារនិងគ្មានសេដ',
          'thorn.name': 'សប្បាយ',
          'thorn.smile': 'ខុ្ញ',
        },
      };
}
